Add Build Platform CVE Database Update
boostsecurityio/poutine pull request #166
Opened 2024-07-17 19:40 UTC by SUSTAPLE117

Adds script to update cve database for build platforms. Fixes #87

2024-07-18 20:35 UTC, fproulx-boostsecurity requested changes

2024-07-18 20:35 UTC, fproulx-boostsecurity commented on opa/populate_build_platform_vuln_database_test.go
> +// +build build_platform_vuln_database
Add instructions to `README.md` maybe on how to use this ? 
Or just here as a comment, since it's more a maintenance thing than user ?

2024-07-18 20:35 UTC, fproulx-boostsecurity commented on scanner/inventory_test.go
> -		},
hmmmm so we have zero test for this now ?
I can find `CVE-2024-2651` in the file and it's `>=0.0,<16.9.7`, so should still match !?

2024-07-18 20:35 UTC, fproulx-boostsecurity commented on opa/populate_build_platform_vuln_database_test.go
> +		{"git", []string{"sparse-checkout", "set", "cves/2020", "cves/2021", "cves/2022", "cves/2023", "cves/2024"}},
we could future proof that by already adding `cves/2025` and `cves/2026` ;p

2024-07-18 20:36 UTC, SUSTAPLE117 commented on scanner/inventory_test.go
> -		},
@fproulx-boostsecurity that version added 80 CVEs to the test and everytime we update it will add more so for the sake of maintenance I removed it

2024-07-18 22:29 UTC, fproulx-boostsecurity commented on scanner/inventory_test.go
> -		},
@SUSTAPLE117 I see, maybe we can find a more recent version that has just like one or two.... does not have to be Gitlab, but at least so we have a basic test

2024-07-19 16:25 UTC, fproulx-boostsecurity approved these changes

2024-07-19 16:39 UTC, merged